services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend_standalone
    ports:
      - "3003:80"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:8003}
      - VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY}
      - VITE_CLERK_SIGN_IN_URL=${VITE_CLERK_SIGN_IN_URL:-/sign-in}
      - VITE_CLERK_SIGN_UP_URL=${VITE_CLERK_SIGN_UP_URL:-/sign-up}
      - VITE_CLERK_AFTER_SIGN_IN_URL=${VITE_CLERK_AFTER_SIGN_IN_URL:-/dashboard}
      - VITE_CLERK_AFTER_SIGN_UP_URL=${VITE_CLERK_AFTER_SIGN_UP_URL:-/dashboard}
      - NODE_ENV=${NODE_ENV:-production}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      start_period: 5s
      retries: 3
