version: "3.8"

services:
  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: youtube_extractor_backend
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=${NEON_DATABASE_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_FRONTEND_API=${CLERK_FRONTEND_API}
      - CLERK_AUDIENCE=${CLERK_AUDIENCE}
      - EMBED_MODEL_NAME=${EMBED_MODEL_NAME:-sentence-transformers/all-MiniLM-L6-v2}
      - PDF_TTF_PATH=${PDF_TTF_PATH:-DejaVuSans.ttf}
      - YOUTUBE_TRANSLATION=${YOUTUBE_TRANSLATION:-en}
      - CORS_ALLOW_ORIGINS=${CORS_ALLOW_ORIGINS:-http://localhost:3003,https://yougen.hellonotionhive.com}
      - APP_ENV=${APP_ENV:-development}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: youtube_extractor_frontend
    ports:
      - "3003:80"
    environment:
      - VITE_API_BASE_URL=https://ygbackend.hellonotionhive.com
      - VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY}
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
