# Production Override for Unified Docker Compose
# Usage: docker compose -f docker-compose-unified.yml -f docker-compose-unified.prod.yml up -d

services:
  backend:
    environment:
      - APP_ENV=production
      - CORS_ALLOW_ORIGINS=https://yougen.hellonotionhive.com
    restart: always

  frontend:
    environment:
      - VITE_API_BASE_URL=https://ygbackend.hellonotionhive.com
      - NODE_ENV=production
    restart: always
