services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: youtube_extractor_backend
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=${NEON_DATABASE_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_FRONTEND_API=${CLERK_FRONTEND_API}
      - CLERK_AUDIENCE=${CLERK_AUDIENCE}
      - EMBED_MODEL_NAME=${EMBED_MODEL_NAME:-sentence-transformers/all-MiniLM-L6-v2}
      - PDF_TTF_PATH=${PDF_TTF_PATH:-DejaVuSans.ttf}
      - YOUTUBE_TRANSLATION=${YOUTUBE_TRANSLATION:-en}
      - CORS_ALLOW_ORIGINS=${CORS_ALLOW_ORIGINS:-http://localhost:3000,http://localhost:3003,https://yougen.hellonotionhive.com}
      - APP_ENV=${APP_ENV:-development}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import requests; requests.get('http://localhost:8003/health')",
        ]
      interval: 30s
      timeout: 10s
      start_period: 5s
      retries: 3
    volumes:
      - .:/app # Mount current directory for development
    working_dir: /app
